### ISSUE TITLE
Generating Token via GET instead of POST

### ISSUE THREAD

**Issue by kieljohn** [vivait/licensing-client#22]
http://api.doc.build/oauth/token?client_id=<client_id>&client_secret=<client_secret>&grant_type=client_credentials 

is appearing in the logs, shouldn't this be in a POST request so once the service switches to HTTPS it will be secured?

**Comment by robcaw** [comment]
Yep you're probably right. This will need enforcing in licensing-client, docbuild-php and licensing

**Comment by jackbentley** [comment]
oAuth2 allows both GET and POST requests to the `oauth/token` endpoint, to retrieve an access token, as well as the ability to put credentials in the authorisation header.

However, both `docbuild-php` and `licensing-client` should be checked to make sure they are at least using a POST request.

**Comment by robcaw** [comment]
I'll add issues to both

**Comment by robcaw** [comment]
licensing-client has been updated (0.4.1), just relying on Transdoc being updated to use  this version. I've created an issue at https://github.com/vivait/TransDoc/issues/37.
